### ISSUE TITLE
'/etc/mcollective' hardcoded in mcollective::actionpolicy.pp

### ISSUE THREAD

**Issue by xraj** [puppet-community/puppet-mcollective#103]
FreeBSD's configuration directory is installed under '/usr/local/etc/mcollective'.

Suggested fixes.

 * Modify mcollective::actionpolicy path to use a policy_dir parameter in string interpolation.
 * Refactor all paths to use a common config_dir parameter

**Comment by igalic** [comment]
fixed in #157
