### ISSUE TITLE
Modify activemq template to support subcollectives

### ISSUE THREAD

**Issue by lvg** [puppet-community/puppet-mcollective#123]
The ActiveMQ XML template only supports the mcollective collective. Multiple subcollectives are not included. In de page http://docs.puppetlabs.com/mcollective/deploy/middleware/activemq.html#authorization-group-permissions there is a sample for how to adjust the template for subcollective support

**Comment by igalic** [comment]
given that we a) don't support middleware anymore, but b) support subcollectives, i'd say this is now fixed.
