### ISSUE TITLE
For ActiveMQ middleware host, manage activemq-wrapper.conf

### ISSUE THREAD

**Issue by jantman** [puppet-community/puppet-mcollective#124]
Just came in to work this morning to find that my MCollective instance had run out of heap space and gone somewhat crazy, preventing puppet runs throughout my environment and spamming notifications. 

While this module support replacing the activemq.xml config with either a different template or a string, it doesn't manage activemq-wrapper.conf (on centos6, /usr/share/activemq/conf/activemq-wrapper.conf) at all, which is where we need to set (a) the actual initial and maximum heap space, and (b) enable JMX so we can actually monitor this.

**Comment by igalic** [comment]
nope.
middleware management is gone.
