### ISSUE TITLE
mco client needs cert, key and ca to issue commands in case of middleware_ssl

### ISSUE THREAD

**Issue by cristifalcas** [puppet-community/puppet-mcollective#125]
If we set middleware_ssl to true, mco client can't ping because of those errors:

mco ping
error 2014/03/11 13:14:22: activemq.rb:306:in `ssl_parameters' Failed to set full SSL verified mode: RuntimeError: cert, key and ca has to be supplied for verified SSL mode

The ping application failed to run, use -v for full error backtrace details: Could not connect to ActiveMQ Server: cert, key and ca has to be supplied for verified SSL mode

Fix:
move cert and key configuration from server to common class:

  mcollective::server::setting { "plugin.activemq.pool.${name}.ssl.cert and key 
  mcollective::common::setting { "plugin.activemq.pool.${name}.ssl.cert and key

**Comment by igalic** [comment]
i'm pretty, and sure, this is already fixed.
