### ISSUE TITLE
Should exclude "path" fact from facts.yaml

### ISSUE THREAD

**Issue by antaflos** [puppet-community/puppet-mcollective#129]
When running `puppet agent -t` manually on the shell of a node the values of the `$PATH` environment variable and thus the `path` fact are almost always different from when run non-manually by Cron or daemon. This results in changes in `/etc/mcollective/facts.yaml`, prompting a restart of Mcollective.

This leads to unnecessary noise and I think the `path` fact should be excluded from `facts.yaml`, just like other dynamic facts.

**Comment by igalic** [comment]
given the positive conclusion of #131, i'm closing this issue.
