### ISSUE TITLE
To install this we should no longer use puppet module install then?

### ISSUE THREAD

**Issue by fullmooninu** [puppet-community/puppet-mcollective#208]
To insttall this we should no longer use puppet module install / forge then?

https://forge.puppetlabs.com/puppetlabs/mcollective <- question derived from the info available here

**Comment by nibalizer** [comment]
You should be able to puppet module install puppet/mcollective

**Comment by fullmooninu** [comment]
Cool, then maybe update the info on the forge?

**Comment by igalic** [comment]
we need a better… redirect… of some form on the forge…

@ryanycoleman ping any idea how to improve the situation on the front?
